apiVersion: v1
kind: Pod
metadata:
  name: nginx-storage
spec:
  containers:
    - name: nginx
      image: nginx
      volumeMounts:
        - name: ephemeral
          mountPath: "/scratch"
    - name: busybox
      image: busybox
      command: ["/bin/sh", "-c"]
      args: ["sleep 1000"]
      volumeMounts:
        - name: ephemeral
          mountPath: "/scartch"
  volumes:
    - name: ephemeral
      emptyDir:
        sizeLimit: 500Mi
